name = "plugbits-reports"
main = "src/index.ts"
compatibility_date = "2024-11-15"

[[kv_namespaces]]
binding = "TEMPLATE_KV"
id = "d624574989f54971a833e53bcd1ef268"
preview_id = "d624574989f54971a833e53bcd1ef268"
